# -*- coding: utf-8 -*-
"""model_preparation

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hjKaU15GFf-X05jhj_nuF9mu5sE8_cCh
"""

import pandas as pd
import numpy as np

df = pd.read_csv('train/train.csv')

from sklearn.model_selection import train_test_split
import sklearn.metrics as sm
from sklearn.ensemble import RandomForestRegressor
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_squared_error,r2_score
imputer = SimpleImputer(strategy='mean')
df_ = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)
# sunshine mean_amount_of_cloud
ft = df_.drop(["sunshine"],axis=1)
tr = df_["sunshine"]
ft_train, ft_test, tr_train, tr_test = train_test_split(ft, tr, test_size=0.3)
regressor = RandomForestRegressor(n_estimators=100)
regressor.fit(ft_train , tr_train)
RandomForestRegressor()

predictions2 = regressor.predict(ft_test)
predictions2

mse = mean_squared_error(tr_test, predictions2)
print("Mean Squared Error:", mse)
print("Median absolute error =", round(sm.median_absolute_error(tr_test, predictions2), 2))
print("Mean absolute error =", round(sm.mean_absolute_error(tr_test, predictions2), 2)) 
print("Test set R2: {:.3f} ".format(regressor.score(ft_test, tr_test)))
r2 = regressor.score(ft_test, tr_test)
print("R-squared:", r2)


import dill as pickle
filename = 'model_v1.pk'
with open(filename, 'wb') as file:
	pickle.dump(regressor, file)
