# -*- coding: utf-8 -*-
"""model_preprocessing

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1si7fMBw_Okctpyt1IPmX4mMnIxgKcm9_
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('train/train.csv')
df_test= pd.read_csv('test/test.csv')
df_y = pd.read_csv('test/y_test.csv')
df_test['sunshine']=df_y

scaler = StandardScaler()
df = scaler.fit_transform(df)
df_test = scaler.fit_transform(df_test)

df.to_csv('train/train.csv', index=False)
df_test['sunshine'].to_csv('test/y_test.csv', index=False)
(df_test.drop(["sunshine"],axis=1)).to_csv('test/test.csv', index=False)
