# -*- coding: utf-8 -*-
"""model_testing

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13EXltjdsfMYp6TLpn5f2ZbBft2sGm50z
"""

import dill as pickle
import pandas as pd
import numpy as np

df_test = pd.read_csv('test/test.csv')
df_y = pd.read_csv('test/y_test.csv')

with open('model_v1.pk','rb') as f:
    loaded_model = pickle.load(f)

predictions2 = loaded_model.predict(df_test)
r2 = loaded_model.score(df_test, df_y)
print("R-squared predict_test:", r2)
